### ISSUE TITLE
Roadmap to language

### ISSUE THREAD

**Issue by mason-bially** [cultlang/craft-lisp#1]
## Interpreter

Principles:
* **Keep It Simple**: Raw lisp syntax, very little sugar, don't modify to support the engine too much.
* **Integrate with Engine**: Where it doesn't complicate things too much prefer integration with the engine.
* **Only Pay For What Is Used**: Plan for a compiler smart enough to drop un-needed information.

### Core

Steps required to do anything

- [ ] Module Object (#5) (take string, parse into AST, load from files, re-evaluate, namespace management)
  - [x] Node types (#2): Makes sure we have all the types to make instances from the parser.
  - [x] Parser (#4)
- [ ] Interpreter Environment Object (globals, evaluation, concurrency management)
  - [ ] Scope: Scope object for the current scope of a function.
  - [x] Evaluater: Using instances as the cell type.
- [ ] Types (#8).
- [ ] Multi-methods (for defining functions).
- [ ] Exceptions/Errors/Signals (#10)
- [ ] Global Library (#11)

### Extras

Extras for hooking into the engine.

- [x] `lisp::PSubroutine` Allows for evaluation using the object.
  - [ ] Extensions for inspecting type signature?
- [ ] `lisp::PMacro` Allows for macro expansion with this object.
- [ ] Support the engine's `craft::types` ABI and type reflection.

### Features

Features for the language

- [ ] Implementation multi-methods (e.g. for certain evaluation steps).
- [ ] Julia style parsing.
  - [ ] C++ style
  - [ ] Python style
- [ ] Prototype compiler (with optional typing)

### Bootstrap

Features required for bootstrapping

- [ ] C++ calling features (to access LLVM and engine). #3

### Interpreted

- [ ] Rewrite the interpreter in the language.

### Compiled

- [ ] Write a compiler.
  - [ ] Support optional typing.

### Features

- [ ] Generate native C++ variations of types
  - Goal: Use generated C++ for the type system.

### Core

- [ ] Rewrite the module system in the language.
- [ ] Rewrite the parser in the language.
    * Write a peg parsing library.
- [ ] Rewrite the environment in the language.

### Features

- [ ] Use generated C++ of the builtin dynamic types for the engine's type system.
